fix calling callback on addScopes
google/GoogleSignIn-iOS pull request #29
Opened 2021-07-19 17:41 UTC by AntonKozlovskyi

2021-07-19 17:42 UTC, AntonKozlovskyi commented
@googlebot I signed it!

2021-07-19 18:42 UTC, petea requested changes
Thanks, Anton!  Could you also apply this fix to the two other locations in GIDSignIn.m where we set "_currentOptions = nil" after executing the callback block?

2021-07-19 18:42 UTC, petea commented on GoogleSignIn/Sources/GIDSignIn.m
> +        GIDSignInCallback callback = [self->_currentOptions.callback copy];
Should be able to do without the copy here.

2021-07-19 18:59 UTC, petea commented on GoogleSignIn/Sources/GIDSignIn.m
> +        GIDSignInCallback callback = [self->_currentOptions.callback copy];
Use two space tabs.

2021-07-19 19:22 UTC, AntonKozlovskyi commented
done

2021-07-19 22:03 UTC, petea approved these changes

2021-07-19 23:04 UTC, merged

2021-11-08 17:44 UTC, tgun1370 reviewed
`AntonKozlovskyi:Fix_missing_completion_handler_on_add_scopes`