Hengyul/gid authorization flow processor fake
google/GoogleSignIn-iOS pull request #312
Opened 2023-05-22 18:23 UTC by henryhl22321

Create a new branch from pin-GIDAuthorizationFlowProcessor-fake in order to merge the change on refactorGSI

2023-05-24 23:12 UTC, ch40w31 approved these changes

2023-05-24 23:12 UTC, ch40w31 commented on GoogleSignIn/Tests/Unit/GIDSignInTest.m
> +  _profileDataFetcher = [[GIDFakeProfileDataFetcher alloc] init];
Swap these two lines to match the order of variables being passed to GIDSignIn's initializer below.

2023-05-25 21:27 UTC, mdmathias requested changes

2023-05-25 21:27 UTC, mdmathias commented on GoogleSignIn/Sources/GIDAuthorizationFlowProcessor/Implementations/Fakes/GIDFakeAuthorizationFlowProcessor.m
> +  return YES;
It might be more clear to return `NO` here since we assert "Not implemented" right above.

2023-05-26 17:28 UTC, mdmathias approved these changes

2023-05-26 20:07 UTC, merged